### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Perdition0** [L061571C5/TubbBot#43]
![Screenshot_٢٠٢١٠٢٢٤_١٢١٧٥٧](https://user-images.githubusercontent.com/46451302/108978198-69fa8900-769a-11eb-88c1-a80718b18839.jpg)

**Comment by L061571C5** [comment]
As mentioned [here](https://github.com/DevSnowflake/youtube-sr/issues/11), use Node.js version `>=14`.
